### PR TITLE
List grid view

### PR DESCRIPTION
**Pull request by ranjini1992**

### CODE REVIEW

**Comment by vshivam** [comment]
do you think you can merge it in with fixes branch ? there are some ui changes in there and it will conflict the changes.

**Comment by ranjini1992** [comment]
when do we plan to merge ui fixes to master? i can fix the conflicts and push after that

**Comment by vshivam** [comment]
I am not really sure if we need a list view for the notes in the home page. It's a really small vertical space anways and adding the list doesn't do anything. I would say let's move it into the place inside of a book, where the user might have a lot of notes for a particular book. 

I would also prefer the list view for the books that are listed on the home page.

**Comment by vshivam** [comment]
The ui also looked weird in the list view for some reason but it's possible that I could not resolve the merge conflicts properly.

**Pull request merged**
